import type { Province } from "./types";

/**
 * Comprehensive list of Canadian cities/towns by province.
 * Includes all municipalities with population ~10,000+ (2021 Census)
 * plus notable smaller real estate markets.
 * Sorted alphabetically within each province.
 */
export const CITIES_BY_PROVINCE: Record<Province, string[]> = {
  Alberta: [
    "Airdrie",
    "Beaumont",
    "Brooks",
    "Calgary",
    "Camrose",
    "Canmore",
    "Chestermere",
    "Cochrane",
    "Cold Lake",
    "Edmonton",
    "Fort McMurray",
    "Fort Saskatchewan",
    "Grande Prairie",
    "High River",
    "Hinton",
    "Lacombe",
    "Leduc",
    "Lethbridge",
    "Lloydminster",
    "Medicine Hat",
    "Morinville",
    "Okotoks",
    "Olds",
    "Peace River",
    "Penhold",
    "Red Deer",
    "Sherwood Park",
    "Spruce Grove",
    "St. Albert",
    "Stony Plain",
    "Strathmore",
    "Sylvan Lake",
    "Taber",
    "Wetaskiwin",
  ],

  "British Columbia": [
    "Abbotsford",
    "Armstrong",
    "Burnaby",
    "Campbell River",
    "Castlegar",
    "Chilliwack",
    "Colwood",
    "Comox",
    "Coquitlam",
    "Courtenay",
    "Cranbrook",
    "Dawson Creek",
    "Delta",
    "Duncan",
    "Esquimalt",
    "Fernie",
    "Fort St. John",
    "Hope",
    "Invermere",
    "Kamloops",
    "Kelowna",
    "Ladysmith",
    "Lake Country",
    "Langford",
    "Langley",
    "Maple Ridge",
    "Merritt",
    "Mission",
    "Nanaimo",
    "Nelson",
    "New Westminster",
    "North Cowichan",
    "North Vancouver",
    "Oliver",
    "Osoyoos",
    "Parksville",
    "Peachland",
    "Penticton",
    "Pitt Meadows",
    "Port Alberni",
    "Port Coquitlam",
    "Port Moody",
    "Powell River",
    "Prince George",
    "Prince Rupert",
    "Qualicum Beach",
    "Quesnel",
    "Revelstoke",
    "Richmond",
    "Salmon Arm",
    "Sidney",
    "Sooke",
    "Squamish",
    "Summerland",
    "Surrey",
    "Terrace",
    "Trail",
    "Vancouver",
    "Vernon",
    "Victoria",
    "View Royal",
    "West Kelowna",
    "West Vancouver",
    "Whistler",
    "White Rock",
    "Williams Lake",
  ],

  Manitoba: [
    "Brandon",
    "Dauphin",
    "Morden",
    "Portage la Prairie",
    "Selkirk",
    "Steinbach",
    "Stonewall",
    "The Pas",
    "Thompson",
    "Winkler",
    "Winnipeg",
  ],

  "New Brunswick": [
    "Bathurst",
    "Campbellton",
    "Dieppe",
    "Edmundston",
    "Fredericton",
    "Grand Falls",
    "Miramichi",
    "Moncton",
    "Oromocto",
    "Quispamsis",
    "Riverview",
    "Rothesay",
    "Sackville",
    "Saint John",
    "Shediac",
    "Sussex",
    "Woodstock",
  ],

  "Newfoundland and Labrador": [
    "Bay Roberts",
    "Carbonear",
    "Clarenville",
    "Conception Bay South",
    "Corner Brook",
    "Gander",
    "Grand Falls-Windsor",
    "Happy Valley-Goose Bay",
    "Labrador City",
    "Mount Pearl",
    "Paradise",
    "Portugal Cove-St. Philip's",
    "St. John's",
    "Stephenville",
    "Torbay",
  ],

  "Nova Scotia": [
    "Amherst",
    "Antigonish",
    "Bridgewater",
    "Cape Breton (Sydney)",
    "Coldbrook",
    "Dartmouth",
    "Enfield",
    "Glace Bay",
    "Halifax",
    "Kentville",
    "Lower Sackville",
    "Lunenburg",
    "New Glasgow",
    "New Minas",
    "Sackville",
    "Stellarton",
    "Sydney",
    "Truro",
    "Wolfville",
    "Yarmouth",
  ],

  Ontario: [
    "Ajax",
    "Amherstburg",
    "Arnprior",
    "Aurora",
    "Bancroft",
    "Barrie",
    "Belleville",
    "Bracebridge",
    "Bradford West Gwillimbury",
    "Brampton",
    "Brantford",
    "Brockville",
    "Burlington",
    "Caledon",
    "Cambridge",
    "Carleton Place",
    "Clarington",
    "Cobourg",
    "Collingwood",
    "Cornwall",
    "East Gwillimbury",
    "Elliot Lake",
    "Essa",
    "Essex",
    "Fort Erie",
    "Georgina",
    "Gravenhurst",
    "Greater Napanee",
    "Grimsby",
    "Guelph",
    "Haldimand County",
    "Halton Hills",
    "Hamilton",
    "Hawkesbury",
    "Huntsville",
    "Ingersoll",
    "Innisfil",
    "Kanata",
    "Kawartha Lakes",
    "Kemptville",
    "Kenora",
    "King",
    "Kingston",
    "Kingsville",
    "Kitchener",
    "LaSalle",
    "Lakeshore",
    "Leamington",
    "Lincoln",
    "Lindsay",
    "London",
    "Markham",
    "Midland",
    "Milton",
    "Mississauga",
    "Mono",
    "New Tecumseth",
    "Newmarket",
    "Niagara Falls",
    "Niagara-on-the-Lake",
    "Norfolk County",
    "North Bay",
    "Oakville",
    "Orangeville",
    "Orillia",
    "Orleans",
    "Oshawa",
    "Ottawa",
    "Owen Sound",
    "Parry Sound",
    "Pelham",
    "Pembroke",
    "Penetanguishene",
    "Perth",
    "Petawawa",
    "Peterborough",
    "Pickering",
    "Port Colborne",
    "Port Hope",
    "Prince Edward County",
    "Quinte West",
    "Richmond Hill",
    "Russell",
    "Sarnia",
    "Sault Ste. Marie",
    "Shelburne",
    "Simcoe",
    "Smiths Falls",
    "South Stormont",
    "St. Catharines",
    "St. Thomas",
    "Stittsville",
    "Stratford",
    "Strathroy-Caradoc",
    "Sudbury",
    "Tecumseh",
    "Thorold",
    "Thunder Bay",
    "Tillsonburg",
    "Timmins",
    "Toronto",
    "Uxbridge",
    "Vaughan",
    "Wasaga Beach",
    "Waterloo",
    "Welland",
    "Whitby",
    "Whitchurch-Stouffville",
    "Wilmot",
    "Windsor",
    "Woodstock",
    "Woolwich",
  ],

  "Prince Edward Island": [
    "Charlottetown",
    "Cornwall",
    "Montague",
    "Stratford",
    "Summerside",
  ],

  Quebec: [
    "Alma",
    "Amos",
    "Baie-Comeau",
    "Beaconsfield",
    "Beauport",
    "Bécancour",
    "Beloeil",
    "Blainville",
    "Boisbriand",
    "Boucherville",
    "Brossard",
    "Candiac",
    "Chambly",
    "Châteauguay",
    "Côte-Saint-Luc",
    "Deux-Montagnes",
    "Dolbeau-Mistassini",
    "Dollard-des-Ormeaux",
    "Dorval",
    "Drummondville",
    "Gaspé",
    "Gatineau",
    "Granby",
    "Joliette",
    "Kirkland",
    "L'Ancienne-Lorette",
    "L'Assomption",
    "La Prairie",
    "La Tuque",
    "Lac-Brome (Knowlton)",
    "Lachute",
    "Laval",
    "Lévis",
    "Longueuil",
    "Magog",
    "Mascouche",
    "Matane",
    "Mirabel",
    "Mont-Laurier",
    "Mont-Royal",
    "Mont-Saint-Hilaire",
    "Mont-Tremblant",
    "Montréal",
    "Nicolet",
    "Pointe-Claire",
    "Prévost",
    "Québec City",
    "Repentigny",
    "Richelieu",
    "Rimouski",
    "Rivière-du-Loup",
    "Rosemère",
    "Rouyn-Noranda",
    "Saguenay",
    "Saint-Basile-le-Grand",
    "Saint-Bruno-de-Montarville",
    "Saint-Colomban",
    "Saint-Constant",
    "Saint-Eustache",
    "Saint-Georges",
    "Saint-Hyacinthe",
    "Saint-Jean-sur-Richelieu",
    "Saint-Jérôme",
    "Saint-Lambert",
    "Saint-Lazare",
    "Saint-Lin-Laurentides",
    "Saint-Sauveur",
    "Sainte-Adèle",
    "Sainte-Anne-des-Plaines",
    "Sainte-Julie",
    "Sainte-Marthe-sur-le-Lac",
    "Sainte-Thérèse",
    "Salaberry-de-Valleyfield",
    "Sept-Îles",
    "Shawinigan",
    "Sherbrooke",
    "Sorel-Tracy",
    "Terrebonne",
    "Thetford Mines",
    "Trois-Rivières",
    "Val-d'Or",
    "Varennes",
    "Vaudreuil-Dorion",
    "Victoriaville",
    "Westmount",
  ],

  Saskatchewan: [
    "Estevan",
    "Humboldt",
    "Lloydminster",
    "Martensville",
    "Meadow Lake",
    "Melfort",
    "Moose Jaw",
    "North Battleford",
    "Prince Albert",
    "Regina",
    "Saskatoon",
    "Swift Current",
    "Warman",
    "Weyburn",
    "Yorkton",
  ],
};

/** Flat list of all cities with their province for quick lookup */
export const ALL_CITIES: { city: string; province: Province }[] =
  (Object.entries(CITIES_BY_PROVINCE) as [Province, string[]][]).flatMap(
    ([province, cities]) => cities.map((city) => ({ city, province }))
  );

/** Get cities for a given province */
export function getCitiesForProvince(province: Province): string[] {
  return CITIES_BY_PROVINCE[province] ?? [];
}
